export const ORDER_STATUS = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  PICKED_UP: "PICKED UP",
  IN_TRANSIT: "IN TRANSIT",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

export const DELIVERY_PRIORITY = {
  STANDARD: "STANDARD",
  EXPRESS: "EXPRESS",
};

export const PAYMENT_METHOD = {
  CASH: "CASH",
  COD: "COD",
};